### ISSUE TITLE
Jupyter missing from setup file

### ISSUE THREAD

**Issue by swiggumj** [nanograv/timing_analysis#14]
I'm going through the process of installing everything and setting up my `IPTA_Env` environment and jupyter doesn't get installed through all of that. I think it's as simple as adding a line to timing_analysis setup.py, but in the meantime, I'm just doing `mamba install -c conda-forge jupyter`.

**Comment by cuantar** [comment]
`jupyter` is added to `setup.py` in the GitHubActions branch

**Comment by rossjjennings** [comment]
PR #21 solves this.
